# List all available commands.
default:
    @just --list --unsorted

# Add a package to the given day.
add package day:
    cargo add {{package}} --package day-{{day}}

# Create a new folder for the given day.
create day:
    if ! command -v cargo generate &> /dev/null; then cargo install cargo-generate; fi
    cargo generate --path ./daily-template --name day-{{day}}
    git switch -c 2025/day-{{day}}
    git add .
    git commit -m "Set up day-{{day}}."
    git push --set-upstream origin 2025/day-{{day}}

# Run the given day.
run day:
    cargo run --bin day-{{day}}

# Run tests for the given day.
test day:
    cargo test --bin day-{{day}}

# Merge the given day into main.
merge day:
    git push
    git switch main
    git merge --no-ff 2025/day-{{day}} -m "Merge branch '2025/day-{{day}}'"
    git push
    git push origin --delete 2025/day-{{day}}
    git fetch --prune
